fixes (#7)
- add readme
- add requirements file
- fix var check
- fix pylint issues

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -11,8 +11,20 @@ exit_code=0
 for file in $(git diff-index --cached --name-only -z ${against}); do
   # Run shellcheck on shell scripts
   if command -v shellcheck &> /dev/null ; then
-    if [[ "${file}" == "*.sh" ]] || [[ "${file}" == "*.bash" ]] || [[ "${file}" == "*.ksh" ]] || [[ '#!/bin/bash' == $(head -n1 "${file}") ]] || [[ '#!/bin/sh' == $(head -n1 "${file}") ]]|| [[ '#!/bin/ksh' == $(head -n1 "${file}") ]]; then
+    if [[ "${file}" == "*.sh" ]] || [[ "${file}" == "*.bash" ]] || [[ "${file}" == "*.ksh" ]]; then
       ret_comment=$(shellcheck "${file}")
+      ret_code=$?
+      if [[ ${exit_code} -eq 0 ]] && [[ ${ret_code} -ne 0 ]]; then
+        echo "ERROR: ${ret_comment}"
+        exit_code=1
+      fi
+    fi
+  fi
+
+  # Run pylint on python scripts
+  if command -v pylint &> /dev/null ; then
+    if [[ "${file}" == "*.py" ]]; then
+      ret_comment=$(pylint "${file}")
       ret_code=$?
       if [[ ${exit_code} -eq 0 ]] && [[ ${ret_code} -ne 0 ]]; then
         echo "ERROR: ${ret_comment}"
